### ISSUE TITLE
Method to pipe commands into each other.

### ISSUE THREAD

**Issue by syntaxseed** [syntaxseed/terminalfaker#3]
A method to parse out piped commands, execute them in order & pass output of first to input of second & so on.

**Comment by ghost** [comment]
Hi, interested in contributing. I haven't looked too deep in the code yet, but this method seems like it would be on the `Terminal` object, was that your expectation?

**Comment by syntaxseed** [comment]
@jacob-sbu ... Yes, in terminal.js there is a keypress event listener (around line 426) which is where the line entered at the prompt is parsed & the command looked up & run.

This is where the line should be split at pipes & commands run in sequence. Might need to refactor this and create a recursive command parser? Hm.

**Comment by ghost** [comment]
I think a recursive function might have to be structured counter-intuitively (could just be me though). It would need to call `runCommand` for the input arrays in reverse so that it mimicked the left-to-right execution of piped commands (stdout to stdin). I thought a `.reduce`-based solution might work, going in that direction now. Let me know if I'm off-base on that.

**Comment by syntaxseed** [comment]
Sounds good.

**Comment by syntaxseed** [comment]
Implemented in PR #17.
